// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibogclceyjtldfwmeyxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlib2djbGNleWp0bGRmd21leXhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNTU2ODgsImV4cCI6MjA3MTczMTY4OH0.kMMCG75ozYFUkVKQbyR61fMB9O-YCfYbJAJjZR6Rty0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});